#!/usr/bin/env python3
"""Keep fresh-install schema and one-paste SQL Editor bundle in sync.

Edit base database_schema.sql BEFORE the generated marker, or the two module
files, then run this script. --check fails when generated output is stale.
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
MARKER = '-- BEGIN GENERATED WEBSITE MODULES (scripts/build_sql_update.py)'
schema_path = ROOT / 'database_schema.sql'
base = schema_path.read_text().split(MARKER)[0].rstrip() + '\n\n'
modules = '\n\n'.join(
    f'-- SOURCE: supabase/{name}\n' + (ROOT / 'supabase' / name).read_text().rstrip()
    for name in ('participant_management.sql', 'registration_notifications.sql')
)
schema = base + MARKER + '\n' + modules + '\n-- END GENERATED WEBSITE MODULES\n'
bundle = '''-- UPDATE LENGKAP WEBSITE OUTING — 2026-09-23
-- Generated by scripts/build_sql_update.py; jangan edit file ini langsung.
-- Backup database dahulu. Supabase Dashboard > SQL Editor > New query:
-- tempel SELURUH file ini lalu RUN sebagai postgres. Tidak perlu seed.sql
-- atau fix_admin_login.sql (keduanya bukan bagian update ini).
-- Mencakup seluruh schema/RLS/RPC repo, storage purchases, registrasi,
-- approval + antrean notifikasi, tambah/edit/hapus/impor peserta.
-- Tidak mereset password Auth atau role akun existing. Hash password legacy
-- public.users.password_hash dihapus sesuai migrasi Auth (bukan auth.users).
-- Policy aplikasi lama diganti dengan policy aman dari repo ini. Jika project
-- punya policy kustom, review diff terlebih dahulu. Bucket purchases tetap public
-- sesuai schema website. Custom schema di luar repo perlu migrasi tersendiri.
-- Transaksional: error => ROLLBACK semua perubahan dalam file ini.
-- Setelah sukses, deploy index.html terbaru, logout/login, lalu jalankan
-- supabase/check_website_update.sql. Notif website menggunakan polling 30 detik.
BEGIN;
SET LOCAL lock_timeout = '10s';

''' + schema + '\nCOMMIT;\n'
outputs = {schema_path: schema, ROOT / 'supabase/update_website.sql': bundle}
stale = [str(p.relative_to(ROOT)) for p, text in outputs.items() if not p.exists() or p.read_text() != text]
if '--check' in sys.argv:
    if stale:
        sys.exit('SQL generated files are stale: ' + ', '.join(stale))
    print('SQL generated files are in sync.')
else:
    for p, text in outputs.items():
        p.write_text(text)
    print('Updated database_schema.sql and supabase/update_website.sql')
